### ISSUE TITLE
About the parameter `segment_duration`

### ISSUE THREAD

**Issue by JDYG** [hamarh/HMNet_pth#1]
Hi, 
What is the parameter which[ is used in](https://github.com/hamarh/HMNet_pth/blob/5a80afbed2d9d0bb21505e6e77b1527e31bf3dca/experiments/detection/scripts/train.py#L172) `train.py` as `config.segment_duration`？I want to use the model `hmnet_B1_yolox.py`, however, I found the `segment_duration` is not defined in `TrainSettings`.

Should the `segment_duration` be 1000 in those modes that don't use tbptt? As [used in the file](https://github.com/hamarh/HMNet_pth/blob/5a80afbed2d9d0bb21505e6e77b1527e31bf3dca/hmnet/dataset/gen1.py#L237) `gen1.py`.

Could you please give more explanation about `TRAIN_DURATION`, `DELTA_T`, `N_SEGMENTS` and `SEGMENT_DURATION`? I am very confused about these parameters.

Thank you

**Comment by hamarh** [comment]
Hello,

Sorry to hear about the error.
I have fixed `train.py` to run without `segment_duration` (commit c815056).
When `segment_duration` is not defined, `train.py` now skips `split_into_segments` and inputs the whole event sequence into a model.

The meaning of the parameters for TBPTT is as follows:
We load a sequence of event data for training with `TRAIN_DURATION` [us] length.
The sequence data is split into subsequences for TBPTT.
`SEGMENT_DURATION` defines the length of the subsequences in [us], and `N_SEGMENTS` defines the number of subsequences.
`DELTA_T` defines a size of a timestep of a model, i.e., the model will compute `(SEGMENT_DURATION / DELTA_T)` steps in one forward path.
I will add comments in the config files.

Thank you
